/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ServiceType = IDL.Variant({
  'PediatricExamAndCleaning' : IDL.Null,
  'PeriodontalScaling' : IDL.Null,
  'BotoxConsultForMigraines' : IDL.Null,
  'Extraction' : IDL.Null,
  'InvisalignConsult' : IDL.Null,
  'HygieneAndExam' : IDL.Null,
  'Hygiene' : IDL.Null,
  'BotoxConsultForCosmetic' : IDL.Null,
  'FirstExamAndXray' : IDL.Null,
  'CrownAndExam' : IDL.Null,
  'ExtractionConsult' : IDL.Null,
});
export const Appointment = IDL.Record({
  'serviceType' : ServiceType,
  'contactInfo' : IDL.Text,
  'date' : Time,
  'patientName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'book' : IDL.Func([IDL.Text, IDL.Text, Time, ServiceType], [], []),
  'cancel' : IDL.Func([IDL.Nat], [], []),
  'getAll' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPastAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getUpcoming' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
  'searchByService' : IDL.Func(
      [ServiceType],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'serviceTypeToText' : IDL.Func([ServiceType], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ServiceType = IDL.Variant({
    'PediatricExamAndCleaning' : IDL.Null,
    'PeriodontalScaling' : IDL.Null,
    'BotoxConsultForMigraines' : IDL.Null,
    'Extraction' : IDL.Null,
    'InvisalignConsult' : IDL.Null,
    'HygieneAndExam' : IDL.Null,
    'Hygiene' : IDL.Null,
    'BotoxConsultForCosmetic' : IDL.Null,
    'FirstExamAndXray' : IDL.Null,
    'CrownAndExam' : IDL.Null,
    'ExtractionConsult' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'serviceType' : ServiceType,
    'contactInfo' : IDL.Text,
    'date' : Time,
    'patientName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'book' : IDL.Func([IDL.Text, IDL.Text, Time, ServiceType], [], []),
    'cancel' : IDL.Func([IDL.Nat], [], []),
    'getAll' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getAllAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPastAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getUpcoming' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByPatient' : IDL.Func([IDL.Text], [IDL.Vec(Appointment)], ['query']),
    'searchByService' : IDL.Func(
        [ServiceType],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'serviceTypeToText' : IDL.Func([ServiceType], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };